-- "user" definition

-- Drop table

-- DROP TABLE user;

CREATE TABLE IF NOT EXISTS "USER" (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar NULL,
	login varchar NULL,
	name varchar NULL,
	birthday date NULL,
	CONSTRAINT user_pk PRIMARY KEY (id),
	CONSTRAINT user_un UNIQUE (email)
);

-- ratings definition

-- Drop table

-- DROP TABLE filmorate.ratings;

CREATE TABLE IF NOT EXISTS ratings (
	id int4 NOT NULL,
	name varchar NULL,
	CONSTRAINT ratings_pk PRIMARY KEY (id),
	CONSTRAINT ratings_un UNIQUE (name)
);


-- film definition

-- Drop table

-- DROP TABLE film;

CREATE TABLE IF NOT EXISTS film (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar NULL,
	description varchar(200) NULL,
	release_date date NULL,
	duration int2 NULL,
	rating_id int4 NULL,
	CONSTRAINT film_pk PRIMARY KEY (id),
	CONSTRAINT film_un UNIQUE (name, release_date),
	CONSTRAINT film_rating_fk FOREIGN KEY (rating_id) REFERENCES ratings(id) ON DELETE SET NULL
);


-- genres definition

-- Drop table

-- DROP TABLE genres;

CREATE TABLE IF NOT EXISTS genres (
	id int4 NOT NULL,
	name varchar NULL,
	CONSTRAINT genres_pk PRIMARY KEY (id)
);


-- likes definition

-- Drop table

-- DROP TABLE likes;

CREATE TABLE IF NOT EXISTS likes (
	film_id int4 NULL,
	user_id int4 NULL,
	CONSTRAINT likes_un UNIQUE (film_id, user_id),
	CONSTRAINT likes_fk FOREIGN KEY (film_id) REFERENCES film(id) ON DELETE CASCADE,
	CONSTRAINT likes_fk_1 FOREIGN KEY (user_id) REFERENCES "USER"(id) ON DELETE CASCADE
);


-- friends definition

-- Drop table

-- DROP TABLE friends;

CREATE TABLE IF NOT EXISTS friends (
	user_id int4 NULL,
	friend_id int4 NULL,
	confirm bool NULL,
	CONSTRAINT friends_un UNIQUE (user_id, friend_id),
	CONSTRAINT friends_fk FOREIGN KEY (user_id) REFERENCES "USER"(id) ON DELETE CASCADE,
	CONSTRAINT friends_fk_1 FOREIGN KEY (friend_id) REFERENCES "USER"(id) ON DELETE CASCADE
);


-- films_genres definition

-- Drop table

-- DROP TABLE films_genres;

CREATE TABLE IF NOT EXISTS films_genres (
	film_id int4 NOT NULL,
	genre_id int4 NOT NULL,
	CONSTRAINT films_genres_pk PRIMARY KEY (film_id, genre_id),
	CONSTRAINT films_genres_fk FOREIGN KEY (film_id) REFERENCES film(id) ON DELETE CASCADE,
	CONSTRAINT films_genres_fk_1 FOREIGN KEY (genre_id) REFERENCES genres(id) ON DELETE CASCADE
);